apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokedex
  template:
    metadata:
      labels:
        app: pokedex
    spec:
      containers:
        - name: pokedex
          image: ziki142/pokedex:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_DATABASE
              value: pokedex
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
          volumeMounts:
            - name: storage
              mountPath: /var/www/html/storage
      volumes:
        - name: storage
          emptyDir: {}
